<?php

namespace AppBundle\Repository;

/**
 * DomicilioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomicilioRepository extends \Doctrine\ORM\EntityRepository
{
}
