<?php

namespace AppBundle\Repository;

/**
 * FormularioARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormularioARepository extends \Doctrine\ORM\EntityRepository
{
}
