INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Abbate", "Alejandro Agustín", "0391", "Licenciado en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Acosta", "Guillermo Oscar Ariel", "0367", "Ingeniero Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Acosta", "Marcelo Maximiliano", "0106", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Acosta", "Natalia Carolina", "0232", "Licenciada en Geoecología y  Medio Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Aglietto", "Federico", "0329", "Ingeniero Civil y Especialista en Gestión Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Aglietto", "Guillermo", "0335", "Ingeniero Electromecánico y Especialización en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Agretti", "Saúl Emanuel", "0115", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Aiello", "Fernando", "0287", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Alasia", "Eduardo José", "0196", "Ingeniero en Recursos Hídricos");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Alassia", "Mariano Alberto", "064", "Ingeniero Industrial  Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Albelo", "Mariano Felix", "0113", "Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Alberti", "Daniel Jorge", "0108", "Ingeniero Químico e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Alberto", "Ludmila Rita", "081", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Allignani", "Alejandro Amadeo", "0363", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Alonso", "Sebastián Rodrigo", "0361", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Alvarez", "Alejandro Darío", "014", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Alvarez", "María Cecilia", "0230", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("AMBIENTE Y TERRITORIO", "", "0373", "");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Andrés", "Daniel Antonio", "0133", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Andretich", "Stella Maris", "054", "Ingeniera Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Appiolaza", "Pablo Andrés", "084", "Lincenciado en Seguridad, Higiene y Control Ambiental Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Argentieri", "Juan José", "0188", "Ingeniero Químico - Especialización en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Arguello", "Mario Daniel", "062", "Licenciado en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Armas", "Alberto Enrique", "0189", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Arquiola", "Roberto", "0233", "Licenciado en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Audap-Soubie", "Elvira María", "0242", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Azanza", "Marcelo Mario", "043", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Balbi", "Fabián Roberto", "0198", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Balquinta", "Mercedes", "0386", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bandeo", "Silvana Beatriz", "034", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Barbona", "Juan Ramón", "0302", "Licenciado en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Barducco", "Carla Soledad", "0154", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bartolelli", "Soledad Marcela", "0136", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Basabe", "Blanco Enrique", "0112", "Ingeniero en Minas y Especialista en Higiene y Seguridad en el Trabjo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bassi", "Carlos René", "0110", "Licenciado en Gestión Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Batistelli", "José Luis", "0371", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Baud", "Leandro", "0294", "Ingeniero Civil - Ingeniero Especialista en Ingeniería Sanitaria");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bela", "María Laura", "0289", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bellandi", "Eliana Noemi", "0135", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bellezze", "Claudio Antonio", "0243", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Belloso", "Claudio Oscar", "060", "Licenciado en Química Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Benassi", "Francisco", "0319", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Benitez", "Fernando Javier", "ET", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Berardozzi", "María Emilia", "0208", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bernabeu", "Alejandro Enrique", "0194", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Berros", "María Laura", "0228", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bersano", "Claudio", "069", "Ingeniero Mecánico - Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bertaina", "María Laura", "0128", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bertozzi", "Eduardo Gabriel", "050", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bin", "María Soledad", "0121", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bisciglia", "Miguel", "0313", "Ingeniero Mecánico y Electrisista");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Blanco", "Daniel Eduardo", "0193", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Blanco", "Rosana Graciela", "0349", "Ingeniera Civil y Especialista en Management Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Blasco", "Viviana Lucia", "0109", "Licenciada en Química y Especialista en Ciencias Químicas y Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Boffa", "Guillermo Antonio", "0357", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bohun", "Marcelo", "0346", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bompadre", "Laura", "0122", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bonavia", "María de los Ángeles", "0403", "Licenciada en Seguridad y Salud Ocupacional");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bongiorno", "Daniela", "012", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bongiorno", "Rubén Mauricio", "042", "Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Borda", "Rodrigo Lisandro", "076", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Borda", "Sergio Eladio", "027", "Licenciado en Ciencias Geológicas");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bordoni", "Edo Alberto", "010", "Ingeniero Químico e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Borio", "Juan Carlos", "032", "Licenciado en Organización Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bortolato", "Marta Alejandra", "0145", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Brandolisio", "Ariel", "0244", "Ingeniero Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bratovich", "Alejandra", "0134", "Ingeniera Ambienrtal");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Breques", "Mauro Germán", "0272", "Ingeniero Electromecánico y Especialista en Ingeniería Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Brollo", "María Ester", "0271", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Brun", "Rodrigo Sebastián", "0311", "Licenciado en Biotecnología");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Brunori", "Carolina Yolanda", "0139", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Brusa", "Raúl Hugo", "0247", "Ingeniero Químico - Especialización en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bruzzoni", "María Alicia", "018", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Buenavida", "Rocio Isabel", "0192", "Licenciada en Ciencias del Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bustaber", "Raúl José", "0150", "Ingeniero Mecánico e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Bustos", "Adrián Norberto", "0250", "Ingeniero Agrónomo, orientación Fitotecnia");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Buyatti", "Luisina", "0321", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cabaña Figueroa", "Ivana María", "0385", "Ingeniera Agrimensora");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cáceres", "Juan Francisco", "0267", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cado", "Osvaldo Alberto", "0237", "Ingeniero Químico e Ingeniero Sanitario");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cafaro", "Edgardo Danilo", "0336", "Ingeniero en Recursos Hídricos");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Calvelli", "Francisco", "0258", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Calvo", "Walter Cesar", "0347", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Caminos", "José Luis", "0288", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cantarutti", "Ruben Dario", "0182", "Licenciado en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cantor", "Lena Liza", "0286", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cantori", "Ricardo Héctor", "028", "Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cañete", "Mirta Lucía", "0259", "Ingeniera Forestal");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Capella", "Adriana Silvia", "0161", "Ingeniera en Seguridad Ambiental - Licenciada en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cappello", "Noelia Verónica", "0144", "Licenciada en Ciencias del Ambiente y Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cappi", "Marcelo Emanuel", "0191", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cappi", "María Celina", "092", "Licenciada en Geoecología y  Medio Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Carbajo", "Andrés Federico", "066", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Carballada", "Joaquín", "0300", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Carignano", "Magalí Andrea", "0210", "Arquitecta y Licenciada en Seguridad y Salud Ocupacional");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Casadevall", "Aldana", "0197", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cassaro", "Gastón Marcelo", "0209", "Ingeniero Químico - Especialización en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Castro", "Silvana Luisa", "0370", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Catinot", "Armando Raúl", "083", "Ingeniero Laboral e Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cattarozzi", "Andrea Maricel", "048", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cena", "Oscar Daniel", "0283", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cengarle", "Nahuel César", "0308", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cesari", "Andrea", "0301", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Challiol", "Julio Cesar", "0219", "Licenciado en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Chavarini Analía Verónica", "NULL", "0331", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Chavez", "Sergio Gabriel", "033", "Ingeniero Químico e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Chiabrera", "Juan María", "0255", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ciarrocca", "Leandro Jesús María", "0393", "Licenciado en Seguridad y Salud Ocupacional");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Civelli", "Horacio Luis", "0401", "Arquitecto");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Civico", "Rubén Agustín", "0246", "Ingeniero Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cocconi", "Fernando Carlos José", "056", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Colangelo", "Ivan César", "0325", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Colombo", "Oscar", "0358", "Licenciado en Ciencias del Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Conforti", "Ornela Guadalupe", "0269", "Licenciada en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("CONSULTORA DEMISON S.A", "", "0241", "");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Contesti", "Carolina", "0171", "Ingeniera Industrial y Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Coria", "Ignacio Daniel", "085", "Licenciado en Química Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cortassa", "Fernando", "0323", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Corte", "Oscar Aldo", "0350", "Ingeniero Químino y Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cravero", "Ricardo Alberto", "0130", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Cursack", "Alberto Joaqun", "0397", "Ingeniero en Sistemas de Información");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("D´Orto Julio Hernán", "", "0147", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("D´Orto", "Anibal Matias", "0224", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("D'Abate", "María Elena", "0163", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Dabin", "Alfredo Daniel", "0314", "Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("De La Riva", "Gabriela Eleonora", "093", "Ingeniera Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("De Pauli", "Anush Aylen Loana", "0345", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("De Piante Vicin", "Mario Orlando", "0100", "Ingeniero Mecánico e Ingeniero Mecánico Especialista en Higiene y Seguridad Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Decaillet", "Analia Paula", "0296", "Licenciada en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Del Cerro", "Ximena Milagros", "09", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Della Morte", "Leandro Patricio", "0379", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Di Mario", "José Alberto", "0226", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Di Rienzo", "María Belén", "0409", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Díaz Colodrero", "Ángeles Berenice", "0334", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Diaz", "Analía Soledad", "0327", "Ingeniera Química y Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Doldan", "Juan Carlos", "0155", "Licencado en Química - Orientación Analítica");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Domig", "Luis Alberto", "0252", "Ingeniniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Dominguez", "María Paula", "065", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Don", "Danisa", "08", "Licenciada en Geoecología y  Medio Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Durez", "Ricardo Daniel", "0290", "Ingeniero en Seguridad Ambiental y Licenciado en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Echechuri", "Héctor Alcides", "0348", "Arquitecto");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Echeverría", "José Ignacio", "0180", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("ECOTECNA SRL", "", "0231", "");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("EPSA  SRL", "", "0204", "");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Errico", "Jorge Luis Antonio", "072", "Arquitecto");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Espíndola", "Claudia Viviana", "0341", "Bióloga y Especialista en Gestión Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Espinosa", "Hugo", "019", "Licenciado en Seguridad y Salud Ocupacional");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Fagioli", "Lucía", "0277", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Farina", "María Betania", "0299", "Licenciada en Ciencias del Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Fernandez", "Luis José", "082", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Fernandez", "Cecilia Viviana", "0116", "Ingeniera Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Fernández", "José Luis", "156", "Licenciado en Seguridad y Salud Ocupacional");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Fernandez", "Marcos Guillermo", "0342", "Arquitecto");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Fernandez", "Roberto Enrique", "0164", "Bioquímico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Fernandez", "Rubén Gustavo", "0405", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ferrando", "Soledad", "070", "Licenciada en Ciencias del Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ferraris", "Facundo Nicolás", "0394", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Fiasconaro", "Pablo Andrés", "0206", "Licenciado en Saneamiento Ambiental y Licenciado en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Filipowicz", "Luis Angel", "0157", "Licenciado en Química Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Firman", "Gastón Juan Manuel", "055", "Licenciado en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Firman", "Paula Mariángeles", "0170", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Flesia", "Miguel Angel", "0176", "Ingeniero Químico e Ingeniero Laboral Especialista en Ingenieria Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Formicheli", "Rubén Daniel", "057", "Ingeniero en Recursos Hídricos");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Franchi Lambertti", "Flavia", "0190", "Ingeniera Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Francione", "Hugo Carlos", "0322", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Frey", "María Florencia", "0178", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Gabba", "Omar Angel", "025", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Gabellini", "Diana Liza", "051", "Licenciada en Ciencias del Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Gabellini", "Mirian Susana", "035", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Gabellini", "Rubén Omar", "0268", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Galiano", "Romina", "0315", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Garayechevarria", "Inés", "0166", "Licenciada en Química Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("García", "María Daniela", "099", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("García", "Ricardo Hugo", "0356", "Licenciado en Seguridad y Salud Ocupacional");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Garnero", "María Carolina", "024", "Licenciada en Química Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Garnero", "Walter Dario", "0351", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Garrofe", "María Jimena", "0260", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Geremia", "Alberto Oscar", "094", "Ingeniero Mecánico y Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ghilardi", "Maia Aneley", "0214", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Giacometti", "Ana María", "0253", "Licenciada en Biodiversidad");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Giacosa", "Carolina Ana", "089", "Licenciada en Geoecología y  Medio Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Gil", "Daniel Omar", "037", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Gimenez", "Darío Alberto", "0236", "Ingeniero Electricista y  Especialización en Higiene y Seguridad en el Trabajo y Especialista en Ingeniería Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Gimenez", "Norberto Angel", "0103", "Técnico en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Giomette", "Neldo Oscar", "0118", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Giovacchini", "Eladio Andrés", "091", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Gomez Insausti", "Javier", "0338", "Licenciado en Ciencias del Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Gomez", "Carolina Belén", "ET", "Ingeniera Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Gomez", "Ernesto Ariel", "059", "Ingeniero Químico y Especialista en Higieni y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Gonzalez", "Juan Carlos Raúl", "0240", "Ingeniero en Gestión de Siniestros y Licenciado en Sistemas de Protección Contra Siniestros");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Goyenechea", "Cristina Laura", "0200", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Grignafini", "Marilina", "039", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Grisanti", "Melisa", "045", "Licenciada en Ciencias del Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Guglielmotti", "Carolina", "0333", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Guida", "Cecilia Victoria", "0285", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Gutierrez", "Tomás Carlos", "030", "Licenciado en Edafología");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Helguero Juan Manuel", "", "0408", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Herrero", "María Sol", "0132", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("HIDROAR SA", "", "0332", "");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Houriet", "Enrique Carlos", "0374", "Licenciado en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Hurt", "Antonella Valeria", "0238", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ibañez", "Marcelo Hugo", "06", "Ingeniero Laboral - Ingeniero en Construcciones");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Iocco", "Nora Silvia Ana ", "080", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Iudica", "Adriana Claudia", "016", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Jaime", "Diana M.", "022", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Jovovic", "Gabriel Alejandro", "0326", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Kojanovich", "Claudio Andrés", "0398", "Ingeniero Electrisista - Ingeniero laboral y Especialista en Ingeniería Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Koziol", "Esteban Edgardo", "0362", "Licenciado en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Kurgansky", "Pedro Dalibor", "0123", "Ingeniero en Recursos Hídricos");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Lammertyn", "Sofía", "0380", "Licenciada en Ciencias del Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Landeira", "Eduardo luis", "0254", "Ingeniero Mecánico - Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Lattini", "Albano Ezequiel Facundo", "098", "Abogado");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Lauria", "Celina Rosario", "0199", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Leithner", "Marta Susana", "0138", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Leonardini", "Rubén Pablo", "0125", "Ingeniero en Seguridad Ambiental e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Libutti", "Hernán César", "0235", "Licenciado en Seguridad y Salud Ocupacional");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Lisa", "Mauricio Luis", "0169", "Ingeniero Mecánico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Loeschbor", "Roberto Carlos", "0396", "Ingeniero en Electrónica - Ingeniero Laboral - Especialista en Ingeniería Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Lopez", "Monica Elisa", "052", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Lopez", "Néstor Daniel", "0195", "Ingeniero en Construcciones");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Lorenzatti", "Eduardo Antonio", "0227", "Licenciado en Química - Orientación Analítica");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Lucovich", "Guillermo Luis", "071", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Maccario", "Gabriela Carla", "0312", "Licenciada en Saneamiento Ambiental y Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Madariaga", "Soledad", "0179", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Mansilla", "Victor Hugo", "0404", "Técnica en Superior en higiene y Seguridad laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Marasovich", "Elena Silvia", "0153", "Ingeniera Laboral, Especialista en Ingenieria Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Mariani", "Adrián Dario", "0124", "Ingeniero Químico e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Marino", "Patricia Claudia", "0317", "Licenciada en Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Marinovic", "Fernando Ceferino", "0365", "Ingeniero Industrial y Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Marozzi", "María Paula", "0295", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Martín", "Hernán Francisco", "015", "Ingeniero Industrial y Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Martinet", "Roxana Mariel Guadalupe", "078", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Martinez", "Angel Rafael", "0137", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Martinez", "Diego Germán", "0129", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Masciarelli", "Silvina Gisella", "090", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Mastrizzo", "Pablo Andrés", "0265", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Mastrogiovanni", "Norberto Angel", "0284", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Mayol", "Carlos Francisco Modesto", "0159", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Mazalan", "Pablo Alberto", "087", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Mechaly", "Jorge Emilio", "011", "Ingeniero Químico e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Mehring", "Analía", "0337", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Mehring", "Nadia", "0316", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Melidoro", "Javier Ariel", "0215", "Ingeniero de Alimentos");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Mengoni", "Carolina Soledad", "0276", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Merlo", "María Belen", "0158", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Michea", "Gastón", "0378", "Técnico Universitario en Evaluación Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Milesi", "Nestor Angel", "096", "Ingeniero en Recursos Hídricos");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Mina", "Juan Miguel", "0274", "Ingeniero Electricista- Especialista en Higiene y Seguridad en el Trabajo - Especialista en Ingeniería Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Molina", "Melanie", "0344", "Arquitecta");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Molins", "Magali", "097", "Licenciada en Ciencias del Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Monella", "Diego Iván", "0388", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Monella", "Stefanía L", "0266", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Monfrini", "Alberto Luis", "0234", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Montenegro", "Monica Ester", "0117", "Licenciada en Organización Industrial y Especialista en Huigiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Montesano", "Alejandro", "0340", "Ingeniero Mecánico y Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Montu", "Néstor Juan", "0213", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Morán", "Oscar", "0309", "Ingeniero Químico e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Morán", "Ramiro Fernando", "0389", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Morell", "Mariana Inés", "0248", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Mosca", "Solana", "0412", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Motta", "Mirela Paula", "0366", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Moyano", "Mariana Patricia", "0399", "Licenciada en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Muchiutti", "Ayelen Andrea", "0330", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Muñoz", "Sandra Daniela", "0297", "Licenciada en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Nardone", "Alejandro", "0390", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Nerli", "Fabiana Beatriz", "086", "Ingeniera Química-Ingeniera Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Nieto", "Gonzalo Javier", "0222", "Licenciado en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Notaro", "Hugo Rubén", "0151", "Ingeniero Químico - Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Nuñez", "Gastón Eugenio", "0256", "Licenciado en Seguridad, Higiene y Control Ambiental Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ocampo", "Hugo Carlos", "0257", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Oggier", "Francisco Manuel", "029", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Orlando", "Angela", "0292", "Bioquímico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Orlando", "Edgardo", "0291", "Bioquímico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Orzan", "Mauro Alfredo", "0278", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("OXIGENAR SA", "", "0368", "");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pagliano", "María Lina", "0275", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pagliarini", "Luis Enrique", "0167", "Ingeniero Químico - Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pagnutti", "Néstor Raúl", "0152", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pairola", "Arturo Amado", "0141", "Ingeniero laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pallek", "Ana María", "0280", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Palomeque", "Mariana Alejandra", "073", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pampiglioni", "Roberto Carlos", "0264", "Ingeniero Electrónico, Ingeniero Laboral y Especialista en Ingeniería Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Passini", "Rocío Ailiñ", "0281", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Paulin", "Maira Soledad", "0375", "Licenciada en Ciencias del Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Peirone", "Yanina Paula", "0142", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pellegrini", "Javier Agistín", "0186", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Peña", "José Alberto", "0175", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Perales", "Victoria Ines", "0148", "Ingeniera Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pesse", "María Pamela", "021", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Philipp", "Germán Gustavo", "0353", "Ingeniero Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Piculis", "Noelia Melina", "0225", "Abogada");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pieragostini", "Carla Antonela", "0352", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pigozzi", "José Luis", "0229", "Licenciado en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pinatti", "María Cecilia", "0407", "Licenciada en Geoecología y  Medio Ambiente");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pire", "Eduardo Félix", "077", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pirola", "María Evangelina", "0406", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pirona", "Lorena", "017", "Licenciada en Química Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Plaza", "Walter Héctor", "0270", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Plebani", "Sonia", "0411", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Plenkovich", "Gustavo Rafael", "0111", "Ingeniero Electricista e Ingemiero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pombo", "Fernando", "0149", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ponzo", "Viviana Laura", "04", "Licenciada en Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Porcel", "Benjamín", "0101", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Portillo", "Sabrina Beatriz", "0279", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Pozzi", "Wilfredo", "0143", "Ingeniero Agrimensor");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Prevedi", "Fabian Omar", "0184", "Licenciado en Seguridad y Salud Ocupacional");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Primon", "Julio Oscar", "0387", "Técnico Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Principe", "Sabrina Valeria", "0293", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Prono", "Alejandra Rita", "0120", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Prosperi", "Pablo Diego", "0360", "Ingeniero Electricista y Especialista en Ingeniería Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Quaranta", "Claudio Marcelo", "0207", "Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Queglas", "Miguel Ángel", "0320", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Racca", "Emiliano Luis", "0183", "Licenciado en Seguridad y Salud Ocupacional");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Racca", "Gabriel Ricardo", "031", "Ingeniero Químico e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Raffo", "Sofía María", "0318", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ramb", "María Julia", "0273", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ramirez", "Juan Carlos", "044", "Ingeniero Mecánico e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ramonda", "Marina Marta", "0203", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ravelli", "Ariel Marcelo", "0104", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ravelli", "Cristian Orlando", "0339", "Licenciado en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Realini", "Micaela Soledad", "0107", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Reinares", "Isidoro Guillermo", "0160", "Ingeniero Mecánico-Ingeniero Laboral-Especialista en Ingeniería Amboemtal");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Reinoso", "José Luis", "0305", "Ingeniero Mecánico e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Renaudo", "Ricardo Adrián", "0402", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Reyes", "Fabián Miguel", "0119", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Risiga", "María Constanza Cristina", "0221", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ritondale", "Blas Domingo", "041", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rius", "Sabastián", "0263", "Licenciado en Seguridad, Higiene y Control Ambiental Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rivero", "María Julia", "0303", "Licenciada en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rizzo", "Daniel", "020", "Ingeniero Mecánico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rodriguez Scheitlin", "Cecilia", "0306", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rodriguez", "Agustina", "0102", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rodriguez", "Diana Astrid", "0239", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rodriguez", "Lorena Cecilia", "0187", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rodriguez", "María Laura", "0205", "Ingeniera Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rohrmann", "Ivan René", "0381", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rojas", "Sebastián Isaác", "023", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Romano", "Leandro Andrés", "0343", "Ingeniero Químico y Especialista en Higieni y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Romos", "Daniel Eduardo", "01", "Ingeniero en Seguridad Ambiental y Licenciado en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ronsoni", "Fernando Ariel", "0201", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rossi", "Gilda Lorena", "0217", "Arquitecta");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rosso", "Paola Soledad", "038", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Rotela", "Verónica Liliana", "068", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Roude", "Eduardo Alfredo", "049", "Ingeniero en Recursos Hídricos");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Routier", "María Aneley", "0384", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ruas", "María Fernanda", "0395", "Ingeniera Química y Especialista en Ingeniería Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ruiz Stival", "Juan Carlos", "047", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Ruiz", "Marín Alejandro", "0114", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Saavedra", "Elizabet", "061", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Sacripanti", "Adrian Humberto", "0172", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Saigo", "Mario", "0324", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Salichs", "Adrián", "046", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Salinas", "Mauricio Adrián", "0376", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Saltaleggio", "Melina Paola", "0181", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Sanseverino", "Cristina Beatriz", "063", "Licenciada en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Santarelli", "Silvana", "0162", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Santinelli", "Marina", "067", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Saravia", "Rubén Armando", "0211", "Ingeniero en Recursos Hídricos");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Scarafía", "Mario Danilo", "0355", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Scartossi", "Luis Pedro", "036", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Scime", "Sabrina Ayelen", "0245", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Scotto", "Roberto Oscar", "03", "Ingeniero Industrial y Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Senn", "Jorge Fabián", "0410", "Ingeniero Agrónomo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("SERMAN Y ASOCIADOS S.A.", "", "0223", "");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("SERVICIOS  ECOLOGICOS ROSARIO SRL", "", "0307", "");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Sfeir", "María Verónica", "05", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Sferco", "Silvina", "0354", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Sica", "Cintia Cecilia", "075", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Simón", "Cesar Edgardo", "0382", "Licenciado en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Simón", "Martín Pablo", "0249", "Ingeniero Forestal");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Simón", "Raúl Daniel José", "040", "Ingeniero Mecánico y Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Siri", "Juan José", "0251", "Ingeniero en Recursos Hídricos");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Soljan", "Lidia Susana", "0328", "Ingeniera Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Souto", "Lucia", "0168", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Srayh", "Sergio Oscar", "0383", "Ingeniero en Recursos Hídricos");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Stangaferro", "Veronica", "088", "Ingeniera Agronoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Steinmann", "Irene Beatriz", "0259", "Ingeniera Electricista, Ingeniera laboral, y Especialista en Ingeniería Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Suñer", "José Agustín", "079", "Ingeniero Mecánico e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Tagliaferri", "Paulina", "202", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Taylor", "María Alejandra", "0377", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Tedin", "Eugenia Edith", "0392", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Tellechea", "Natalia", "0177", "Ingeniera Química");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Terenzio", "Marcelo Luis", "0146", "Abogado");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Testa", "Federico Juan", "0282", "Ingeniero Agrónomo y Magister en Gestión Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Tinazzo", "Norberto Daniel", "0127", "Ingeniero Químico y Especialista en Ingeniería Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Tissera", "Germán Eduardo", "0369", "Geólogo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Tolosa", "Mauricio Alberto", "0105", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Torres", "José María", "0174", "Ingeniero Químico e Ingeniero Laboral");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Trossero", "Gisela Alejandra", "0220", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Urquiza", "Juan Carlos", "053", "Ingeniero Químico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Valdano", "Franco", "0310", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Valdano", "Mario José", "0218", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Valle Fernando", "", "07", "Licenciado en Química Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Vanelli", "Luis", "0185", "Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Vega", "Oscar Daniel", "0131", "Ingeniero en Construcciones");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Venezia", "Mario José", "0400", "Ingeniero Civil");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Vicco", "Sebastián Ignacio", "058", "Licenciado en Química Industrial y Especialista en Higiene y Seguridad en el Trabajo");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Vidal", "Jorge Alberto", "02", "Licenciado en Edafología e Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Vidoret", "Viviana", "095", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Villa", "José Luis", "0140", "Ingeniero Mecánico - Especialización en Higiene y Seguridad en el Trabajo  - Especialización en Ingeniería Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Villademoros", "Angela Margarita", "0173", "Ingeniera Agrónoma");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Virelaude", "Daniel Enrique", "0262", "Licenciado en Higiene y Seguridad en el Trabajo y Ingeniero en Seguridad Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Vismara", "Natalí Emilse", "0126", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Visnovsky", "Gustavo José", "0372", "Ingeniero Mecácico");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Vizzica", "Virginia", "013", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Vogt", "María Soledad", "026", "Ingeniera Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Volken", "Oscar René", "074", "Ingeniero en Construcciones");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Walton", "Lorena", "0359", "Ingeniera Química y Especialista en Ingeniería Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Weiner", "Germán Jorge", "0212", "Licenciado en Organización Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Wenke", "Matías Sebastián", "0364", "Ingeniero Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Wilhjelm", "Bárbara Aneley", "0298", "Licenciada en Saneamiento Ambiental");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Zanon", "Daniela Matilde", "0304", "Técnica en Superior en Tecnología de Alimentos");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Zucchi", "Beatriz Cecilia", "0165", "Licenciada en Química Industrial");
INSERT INTO perito (apellido, nombre, nroRegistro, profesion) VALUES ("Zurcher", "Carolina", "216", "Licenciada en Química Industrial");
